# Generated by Django 4.2.5 on 2023-11-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_data', '0004_alter_webdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdata',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
