# Generated by Django 4.2.6 on 2023-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_data', '0002_alter_webdata_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
